### PR TITLE
Ensure the tests can pass by ignoring two license checks.

### PR DESCRIPTION
**Pull request by whyisjake**
`--ignore=language-subtag-registry,tslib`

> ERROR  Module `language-subtag-registry` has an incompatible license ['ODC-By-1.0'](https://opendatacommons.org/licenses/by/1-0/index.html).
> ERROR  Module `tslib` has an incompatible license ['0BSD'](https://opensource.org/licenses/0BSD).

### CODE REVIEW

**Comment by whyisjake** [comment]
(I am not a lawyer)

These licenses look pretty permissive, but I don't see them here: https://www.gnu.org/licenses/license-list.en.html

**Comment by aaronjorbin** [comment]
0BSD looks fine, it's largely the same as [ISC](https://www.gnu.org/licenses/license-list.en.html#ISC)
ODC-By-1.0 is less clear to me

**Comment by whyisjake** [comment]
Looks like the actual script is MIT licensed, but the database is ODC-By-1.0.

> Update scripts copyright (c) 2013, Matthew Caruana Galizia and licensed under and MIT license.
> The JSON database is licensed an Open Data Commons Attribution License (ODC-BY).

https://github.com/mattcg/language-subtag-registry

**Comment by whyisjake** [comment]
Opened an issue over here too: https://github.com/mattcg/language-subtag-registry/issues/7

**Comment by jeffpaul** [comment]
Some questions from @Otto42 to help guide us here:
- What is `language-subtag-registry` and how is it used?
- Is this specific to data or code?

**Comment by whyisjake** [comment]
Really, this should be moved upstream, [here](https://github.com/WordPress/gutenberg/blob/master/packages/scripts/scripts/check-licenses.js).

**Comment by whyisjake** [comment]
Added a PR here to include ODC-By-1.0.

https://github.com/WordPress/gutenberg/pull/23851

**Comment by ntwb** [comment]
> Added a PR here to include ODC-By-1.0.

> WordPress/gutenberg#23851

✅ Approved

Not sure when the next release of Gutenberg packages will be though

**Comment by whyisjake** [comment]
Need the @wordpress/scripts release done, and then we can bump the version there.

**Comment by whyisjake** [comment]
Merged in #89. 📦 🥳

**Pull request closed without merging**
