### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by whyisjake**

### CODE REVIEW

**Comment by aaronjorbin** [comment]
1) Why didn't this get reviewed? 
2) Why do you think this should be 3.0.0 rather than 2.1.1?

**Comment by ntwb** [comment]
Tough call on if it should be a minor or major semver bump, I think usage of this package would be minimal, and as it's used as a "build tool" specific to WordPress Development the version could go either way, if this was more commonly used then bumping to a major version when dropping a Node.js versions support would be the route I'd take, but again, with such low and specific usage I don't think this matters greatly here

**Comment by whyisjake** [comment]
> 1. Why didn't this get reviewed?

I was trying to get a release out and thought I had the privilege to bump the release on NPM. Looks like only @aaronjorbin has access to this project?

> 2. Why do you think this should be 3.0.0 rather than 2.1.1?

Changing the minimum node version is a [major version change](https://github.com/WordPress/grunt-patch-wordpress/blob/trunk/RELEASING.md#major-minor-or-patch).

**Comment by ntwb** [comment]
Moving it into the `@wordpress` npm org would expand the number of publishers, partially related: #70

**Pull request merged**
